services:
  agriculture-app:
    container_name: agriculture-app
    image: app-local:latest
    networks:
      - app-network
    build:
      context: .
      dockerfile: ./local.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - agriculture-db
    ports:
      - 8000:8000
      - 5173:5173

    volumes:
      - ./project:/srv/www
  agriculture-db:
    image: mariadb
    container_name: agriculture-db
    networks:
      - app-network
    ports:
      - "3306:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      TZ: "Europe/Riga"
    volumes:
      - ./docker/db/data:/var/lib/mysql
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  app-data:
    external: true
